start php bin/console app:parse-anwalt https://www.anwalt.de 9052 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9054 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9056 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9058 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9060 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9062 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9064 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9066 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9068 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9070 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9072 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9074 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9076 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9078 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9080 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9082 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9084 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9086 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9088 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9090 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9092 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9094 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9096 HomePage
start php bin/console app:parse-anwalt https://www.anwalt.de 9098 HomePage