<?php

namespace AppBundle\Repository\Parsers;

/**
 * ParseUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParseUrlRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLatest($page = 1)
    {
        /*
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT p, a, t
                FROM AppBundle:Post p
                JOIN p.author a
                LEFT JOIN p.tags t
                WHERE p.publishedAt <= :now
                ORDER BY p.publishedAt DESC
            ')
            ->setParameter('now', new \DateTime())
        ;

        return $query->getOneOrNullResult();
        */
    }
}
