<?php

namespace AppBundle\Repository\Parsers;

/**
 * ParseUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParseUrlRepository extends \Doctrine\ORM\EntityRepository
{
}
